# Generated by Django 6.0.4 on 2026-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_meeting_invitetoken_meetingmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmember',
            name='desired_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meetingmember',
            name='desired_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='meetingmember',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingmember',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
