# Generated by Copilot on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meetingmember_desired_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='confirmed_day',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='meeting',
            name='confirmed_end_minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='confirmed_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meeting',
            name='confirmed_recommendation_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='confirmed_start_minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
